// Bakes the design system's CSS into a JS module so the Vercel function can
// serve it without reading node_modules at runtime.
//
// ⚠️ WHY A GENERATED MODULE. A serverless function cannot rely on arbitrary
// files from node_modules being traced into its bundle - only what it imports
// is guaranteed to travel with it. CSS is not importable from Node, so the two
// stylesheets are turned into an ESM module that IS importable, and therefore
// IS bundled. Reading them with fs at request time works locally and fails in
// production, which is the worst possible failure shape.
//
// Runs from `npm run vercel-build` (Vercel) and `postinstall` (here), so the
// generated file always exists and is never committed - it is a copy of a
// dependency, and a committed copy goes stale the moment the DS is republished.
// That is the same trap ds-theme.cjs has in the app, and the reason this is
// generated rather than checked in.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// The BRAND and DENSITY the share host renders in. Prep+Eat, default density -
// there is no density switch on a public page, so "compact" never applies.
const TOKENS = require.resolve('@sebellds/tokens/dist/prep-eat-default.css');
const COMPONENTS = require.resolve('@sebellds/react/styles.css');

const css = [
  `/* @sebellds/tokens – prep-eat, default density. Generated, do not edit. */`,
  readFileSync(TOKENS, 'utf8'),
  `/* @sebellds/react – component styles. Generated, do not edit. */`,
  readFileSync(COMPONENTS, 'utf8'),
].join('\n');

// Read the manifests by path, not by require(): both packages define an
// `exports` map that deliberately does not expose ./package.json, so resolving
// it through the module system throws ERR_PACKAGE_PATH_NOT_EXPORTED.
const versions = ['@sebellds/tokens', '@sebellds/react']
  .map((p) => {
    const manifest = JSON.parse(
      readFileSync(resolve(root, 'node_modules', p, 'package.json'), 'utf8')
    );
    return `${p}@${manifest.version}`;
  })
  .join(', ');

mkdirSync(resolve(root, 'lib'), { recursive: true });
writeFileSync(
  resolve(root, 'lib/ds-css.mjs'),
  `// GENERATED by scripts/build-css.mjs – do not edit, do not commit.\n` +
    `// Source: ${versions}\n` +
    `export const DS_VERSIONS = ${JSON.stringify(versions)};\n` +
    `export const DS_CSS = ${JSON.stringify(css)};\n`
);

console.log(`[build-css] lib/ds-css.mjs written from ${versions} (${css.length} bytes)`);
